name: Caliper Test
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
      - id: chaincode-share-access

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: "Bob"
          clientPrivateKey:
            path: "../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/Bob@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/Bob@org1.example.com/msp/signcerts/cert.pem"
        - name: "John"
          clientPrivateKey:
            path: "../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/John@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/John@org1.example.com/msp/signcerts/cert.pem"
    connectionProfile:
      path: "../fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml"
      discover: true

  - mspid: Org2MSP
    identities:
      certificates:
        - name: "Alice"
          clientPrivateKey:
            path: "../fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/users/Alice@org2.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/users/Alice@org2.example.com/msp/signcerts/cert.pem"
    connectionProfile:
      path: "../fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/connection-org2.yaml"
      discover: true
